#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define TEXTURE_ROWS 200
#define TEXTURE_COLS 200

#define MAX_U8BIT 255
#define MAX_U16BIT 65535

#define MIN_BRUSH_SIZE 1
#define MAX_BRUSH_SIZE 9

#define EMPTY 0
#define WALL 1
#define SAND 2
#define WATER 3
#define FIRE 4
#define SMOKE 5
#define METAL 6
#define STEAM 7
#define TORCH 8

#define SAND_DENSITY 10
#define WATER_DENSITY 8
#define FIRE_DENSITY 2
#define SMOKE_DENSITY 0
#define STEAM_DENSITY 1

#define EMPTY_BASETEMP 20
#define WALL_BASETEMP 20
#define SAND_BASETEMP 20
#define WATER_BASETEMP 20
#define FIRE_BASETEMP 220
#define SMOKE_BASETEMP 105
#define METAL_BASETEMP 20
#define STEAM_BASETEMP 100
#define TORCH_BASETEMP 140

#define FIRE_MINTEMP 106
#define SMOKE_MINTEMP 70

#define EMPTY_MAXTEMP 255
#define WALL_MAXTEMP 255
#define SAND_MAXTEMP 200
#define WATER_MAXTEMP 100
#define SMOKE_MAXTEMP 254
#define METAL_MAXTEMP 200
#define STEAM_MAXTEMP 255 
#define TORCH_MAXTEMP 255

#define EMPTY_SPECIFICHEAT 100
#define WALL_SPECIFICHEAT 255
#define SAND_SPECIFICHEAT 80
#define WATER_SPECIFICHEAT 60
#define FIRE_SPECIFICHEAT 10
#define SMOKE_SPECIFICHEAT 40
#define METAL_SPECIFICHEAT 45
#define STEAM_SPEFICHEAT 100
#define TORCH_SPECIFICHEAT 8